services:
  api_tests:
    image: python:3.12.3-alpine3.20
    build: .
    volumes:
      - .:/test_project
    command: python -m pytest --alluredir=allure_results/ -v
    environment:
      FIRST_API_KEY: ${FIRST_API_KEY}
      SECOND_API_KEY: ${SECOND_API_KEY}
      FIRST_PASSWORD: ${FIRST_PASSWORD}
      SECOND_PASSWORD: ${SECOND_PASSWORD}