services:
  api_tests:
    image: tests
    build: .
    volumes:
      - .:/test_project
    command: /bin/sh -c "pytest --alluredir=allure_results/ -v"
    environment:
      FIRST_API_KEY: ${FIRST_API_KEY}
      SECOND_API_KEY: ${SECOND_API_KEY}
      FIRST_PASSWORD: ${FIRST_PASSWORD}
      SECOND_PASSWORD: ${SECOND_PASSWORD}

  report:
    image: tests
    build: .
    volumes:
      - .:/test_project
    command: /bin/sh -c "allure generate allure_results --clean -o allure_report"
